### ISSUE TITLE
Can koala support a web framework middleware?

### ISSUE THREAD

**Issue by ChenHaoHu** [heiyeluren/koala#3]
Hi, 首先谢谢作者的开源，这个规则引擎非常棒，下面是我对于这个引擎在投产上的一些小疑问🤔️
![image](https://user-images.githubusercontent.com/28889368/120110944-559ac080-c1a2-11eb-8526-179a34b41859.png)
1. 对于部署方面作者准备后面做什么规划？我理解单实例部署没发保证很好的高可用，无法直接用于生产
2. 有没有考虑下作为web框架的前置中间件去控制频率，像gin中的middleware
3. 是否可以直接放在离业务最近的网关上，比如直接做成nginx的一个模块，提供多网关实例间全局的频率控制

**Comment by houseme** [comment]
> Hi, 首先谢谢作者的开源，这个规则引擎非常棒，下面是我对于这个引擎在投产上的一些小疑问🤔️
> ![image](https://user-images.githubusercontent.com/28889368/120110944-559ac080-c1a2-11eb-8526-179a34b41859.png)
> 
> 1. 对于部署方面作者准备后面做什么规划？我理解单实例部署没发保证很好的高可用，无法直接用于生产
> 2. 有没有考虑下作为web框架的前置中间件去控制频率，像gin中的middleware
> 3. 是否可以直接放在离业务最近的网关上，比如直接做成nginx的一个模块，提供多网关实例间全局的频率控制

**Comment by houseme** [comment]
> Hi, 首先谢谢作者的开源，这个规则引擎非常棒，下面是我对于这个引擎在投产上的一些小疑问🤔️
> ![image](https://user-images.githubusercontent.com/28889368/120110944-559ac080-c1a2-11eb-8526-179a34b41859.png)
> 
> 1. 对于部署方面作者准备后面做什么规划？我理解单实例部署没发保证很好的高可用，无法直接用于生产
> 2. 有没有考虑下作为web框架的前置中间件去控制频率，像gin中的middleware
> 3. 是否可以直接放在离业务最近的网关上，比如直接做成nginx的一个模块，提供多网关实例间全局的频率控制

第2点可以参考核心算法， https://github.com/heiyeluren/koala/blob/main/doc/README.md

第3点 你可以去找找openresty的模块！

**Comment by heiyeluren** [comment]
感谢 [houseme](https://github.com/houseme) 的回复~ 点赞！
